### PR TITLE
Website

### PR DESCRIPTION
**Pull request by dscotese**

### CODE REVIEW

**Comment by dscotese** [comment]
I don't remember the discussion about master vs website, so I'm not sure I want to merge this pull request. @scbrown might be able to remind me why we have both.

**Comment by scbrown** [comment]
@dscotese, this is what I found in an email you sent:

>  I just created and switched myself to a branch called "website" which I will keep in sync with the website.  Maybe "livesite" is a better name for it.

You also said you would only merge website into master _after_ you push the website branch live on voluntaryist.com.

**Comment by dscotese** [comment]
Thanks Steve.  I guess I needed to solidify my understanding of branches.  I just made a ["branches"](https://github.com/voluntaryist/site/wiki/branches) page in the Wiki for it.  Since I update the site first and then (later) make sure I post those changes to the website branch, that second thing (merging only _after_ I push to the website branch live) is moot.  So I will proceed with this merge.  To remind myself next time: the reason for master and website branches is that the culture of altering master ONLY through pulls is useful, so I had to have another branch to which I can commit changes I make to the live site.

**Comment by scbrown** [comment]
@dscotese another idea, that might help you out and that is a fairly common branching strategy is called feature branches. With feature branches, you always deploy the website off of master. Any work that needs to be done gets its own (new) branch. Here is the github page that describe this:
https://guides.github.com/introduction/flow

This would also feel more familiar to other developers that want to add something to the site - they would fork the project in github to their own repository and then, when finished, they open a pull request to master to discuss and then get the feature included. 

The advantage for you would be that you only have to remember one branch - master. It's also helpful because each branch you create will have a name that will remind you what the branch is supposed to do.

**Pull request merged**
